---
name: Debian 11

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'
      - 'docker/**'
      - '.github/workflows/docker.yml'
      - '.github/workflows/ubuntu.yml'
      - '.github/workflows/rocky8.yml'
      - '.github/workflows/linter.yml'

  pull_request:
    branches: [ master ]

jobs:
  Debian11:

    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install required packages
      run: |
        apt update -y
    - name: Check PYTHON environment
      run: |
        which python
        which twisted
        python --version
    - name: Configuration
      run: |
        make init
        make vars
    - name: Build 
      run: |
        make src_install
    - name: Environment Check
      run: make exist
     
