
name: RecSync-env installation test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: uubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install -y python-twisted python-requests python-simplejson python-urllib3 git make
    - run: |
        make init || exit
        make vars || exit
    - run: |
        make install || exit
        make exist || exist
