---
name: Rocky8

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'
      - 'examples/*.bash'
      - 'docker/**'
      - '.github/workflows/ubuntu.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/ubuntu.yml'
      - '.github/workflows/linter.yml'

  pull_request:
    branches: [ master ]

jobs:
  Rocky8:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install required packages
      run: |
        dnf update -y
        dnf install -y git make sudo which python3-twisted python-requests python3-simplejson python3-urllib3
    - name: Check PYTHON environment
      run: |
        which python
        which twisted
        python --version
    - name: Configuration
      run: |
        make init
        make vars
    - name: Build 
      run: |
        make src_install
    - name: Environment Check
      run: make exist
