---
name: Rocky8

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'
      - 'examples/*.bash'
      - 'docker/**'
      - '.github/workflows/ubuntu.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/ubuntu.yml'
      - '.github/workflows/linter.yml'

  pull_request:
    branches: [ master ]

jobs:
  Rocky8:

    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:8

    steps:
    - uses: actions/checkout@v3
    - name: Install required packages
      run: |
        dnf -y install dnf-plugins-core
        dnf update -y
        dnf config-manager --set-enabled powertools
        dnf update -y
        dnf -y install "epel-release"
        dnf update -y
        dnf install -y git make sudo tree which
        dnf install -y python3-twisted python3-requests python3-simplejson python3-urllib3
        alternatives --set python /usr/bin/python3
    - name: Check PYTHON environment
      run: |
        which python
        python --version
        which twistd
        twistd --version
    - name: Configuration
      run: |
        make init
        make vars
    - name: Build 
      run: |
        make src_install
    - name: Environment Check
      run: make exist
